version: '3.8'

services:

  backend:
    build: ./backend
    container_name: gameserver-backend
    volumes:
      - ./scripts:/app/scripts
    restart: unless-stopped
    networks:
      - gsnet
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: gameserver-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gsnet

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - gsnet

  db:
    image: postgres:16
    container_name: gameserver-db
    environment:
      POSTGRES_DB: gamestats
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - gsnet

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - gsnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - gsnet

volumes:
  portainer_data:
  pgdata:
  grafana_data:

networks:
  gsnet:
    driver: bridge
